---

- name: "Network  | Interface | Purge | {{ iface_name }} | Setting vars"
  ansible.builtin.set_fact:
    file: "/etc/network/interfaces.d/{{ iface_name }}"

- name: "Network  | Interface | Purge | {{ iface_name }} | Backing-up current config"
  ansible.builtin.copy:
    src: "{{ file }}"
    remote_src: true
    dest: "{{ NW_HC.network_script_dir }}/backup/{{ file | replace('/', NW_HC.validation.backup_path_separator) }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  when: NW.validation.enable | bool

- name: "Network  | Interface | Purge | {{ iface_name }} | Removing interface file"
  ansible.builtin.file:
    path: "{{ file }}"
    state: absent

- name: "Network  | Interface | Purge | {{ iface_name }} | Removing interface from running-config"
  # is necessary for vlan interfaces and so on
  ansible.builtin.command: "{{ item }}"
  loop:
    - "ip addr flush {{ iface_name }}"
    - "ifdown {{ iface_name }}"
    - 'udevadm settle'
    - "ip link delete {{ iface_name }}"
  ignore_errors: true
  changed_when: false
  when: "':' not in iface_name"  # else it will kill the main iface when an alias should get deleted..
