---

- name: Network | Validator | Installing network validation tools
  ansible.builtin.apt:
    name: "{{ NW_HC.validation.packages }}"
    state: present

- name: Network | Validator | Copying validation script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/ansibleguy.linux_networking/activate_network.py.j2'
    dest: "{{ NW_HC.network_script_dir }}/{{ NW_HC.validation.script }}"
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Network | Validator | Copying validation service
  ansible.builtin.template:
    src: 'templates/etc/systemd/system/ansibleguy.linux_networking.activate_network.service.j2'
    dest: "/etc/systemd/system/{{ NW_HC.validation.service }}"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Network | Validator | Starting validation service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ NW_HC.validation.service }}"
    state: started
    no_block: true
  ignore_errors: true
  async: "{{ NW.reload_timeout }}"
  poll: 2

# todo: if networking.service fails to restart it will not display an error (?); keeps old config

- name: Network | Validator | Updating ip used in this execution
  ansible.builtin.set_fact:
    ansible_host: "{{ post_apply_ip }}"
  when: NW.post_apply_ip is defined

- name: Network | Validator | Waiting to re-establish connection
  ansible.builtin.wait_for_connection:
    timeout: "{{ NW.validation.apply_timeout }}"
  register: connection_restore
  ignore_errors: true

- name: Network | Validator | Unable to connect
  ansible.builtin.fail:
    msg: 'It seems like we lost the connection to the target-host.
    This should not happen. (but might so if the ip was changed on purpose..)
    Please check the logs on the target-system!'
  when:
    - connection_restore.failed is defined
    - connection_restore.failed

- name: Network | Validator | Getting network activation logs
  ansible.builtin.command: "journalctl -u {{ NW_HC.validation.service }} --no-pager -n {{ NW_HC.validation.log_output_lines }}"
  register: network_activation
  changed_when: false

- name: Network | Validator | Here are the last logs of the network activation
  ansible.builtin.debug:
    msg: "{{ network_activation.stdout_lines[1:-2] }}"
