---
- name: Installing MariaDB server
  hosts: databases
  vars:
    db_packages:
      - python3-pymysql
      - mariadb-server
    db_service: mariadb
    resources_url: https://raw.githubusercontent.com/joacolopez/ansible2prod/main/control-handlers/
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
    mysql_root_password: debian
  tasks:
    - name: Set ansible_python_interpreter to /usr/bin/python3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: "{{ db_packages }} packages are installed"
      apt:
        name: "{{ db_packages }}"
        state: present
      notify:
      - set db password

    - name: Make sure the database service is running
      service:
        name: "{{ db_service }}"
        state: started
        enabled: true  


#    - name: Create directory if it doesn't exist
#      file:
#        path: /etc/my.cnf.d/
#        state: directory
#        owner: mysql
#        group: mysql
#        mode: '0777'
    
    - name: The {{ config_file_dst }} file has been installed
      get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

#    - name: Ensure /root/.my.cnf file exists with correct credentials
#      template:
#        src: templates/my.cnf.j2
#        dest: /root/.my.cnf
#        owner: root
#        group: root
#        mode: '0600'
    

    
  handlers:
    - name: restart db service
      service:
        name: "{{ db_service }}"
        state: restarted
    
    - name: set db password
      mysql_user:
        #login_unix_socket: /var/run/mysqld/mysqld.sock
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: root
        password: "{{ mysql_root_password }}"