---
- name: 
  hosts: webservers
  pre_tasks:
    - name: pre_tasks message
      debug:
        msg: 'Ensure web server configuration'
  
  roles:
    - myvhost
  
  post_tasks:
    - name: Ensure web root directory exists
      file:
        path: "/var/www/vhosts/{{ ansible_hostname }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'


    - name: HTML content is installed
      copy:
        src: files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}"
        owner: www-data
        group: www-data
        mode: 0755

    - name: post_tasks message
      debug:
        msg: "Web server is configured."