---

NW_HC:
  # you shouldn't have a need to change these settings
  network_script_dir: '/usr/local/sbin/ansibleguy.linux_networking'
  network_apply_timeout: 30  # how long ansible will wait for a re-established ssh connection
  validation:
    script: 'activate_network.py'
    backup_path_separator: '___'
    log_output_lines: 7
    service: 'ansibleguy.linux_networking.activate_network.service'
    packages: ['systemd', 'fping', 'python3']
  sysctl:
    forwarding:
      enable:
        'net.ipv4.ip_forward': 1
        'net.ipv4.conf.all.arp_filter': 0
        'net.ipv4.conf.all.rp_filter': 2
      disable:
        'net.ipv4.ip_forward': 0
    ipv6:
      disable:
        'net.ipv6.conf.all.disable_ipv6': 1
        'net.ipv6.conf.default.disable_ipv6': 1
        'net.ipv6.conf.lo.disable_ipv6': 1
      enable:
        'net.ipv6.conf.all.disable_ipv6': 0
        'net.ipv6.conf.default.disable_ipv6': 0
        'net.ipv6.conf.lo.disable_ipv6': 0
  bonding_modes: [
    'balance-rr', 'active-backup', 'balance-xor', 'broadcast',
    '802.3ad', 'balance-tlb', 'balance-alb',
    0, 1, 2, 3, 4, 5, 6, '0', '1', '2', '3', '4', '5', '6', 'lacp'
  ]

  controller_required_mods: ['netaddr']
