---
- name: Revert version check script deployment
  hosts: all
  become: yes

  vars:
    version_script_dest: /usr/local/bin/check_version.sh
    profile_script_dest: /etc/profile.d/check_version.sh
    remove_zenity: false 
  tasks:
    - name: Remove the version check script from /usr/local/bin
      file:
        path: "{{ version_script_dest }}"
        state: absent

    - name: Remove the script from /etc/profile.d
      file:
        path: "{{ profile_script_dest }}"
        state: absent