---
- name: Manejo de fallas de tareas
  hosts: awx_lab
  vars:
    web_package: apache2
    db_package: mariadb-server
    db_service: mariadb
  
  tasks:
    - name: Check local time
      command: date
      register: command_result
      changed_when: false
    
    - name: Print local time
      debug:
        var: command_result.stdout

    - name: Attempt to set up a webserver
      block:
        - name: Install {{ web_package }} package
          yum:
            name: "{{ web_package }}"
            state: present
          failed_when: web_package == "apache2"
    
      rescue:
        - name: Install {{ db_package }} package
          yum:
            name: "{{ db_package }}"
            state: present
      
      always:
        - name: Start {{ db_service }} service
          service:
            name: "{{ db_service }}"
            state: started