---
- name: Install and configure web service
  gather_facts: no
  hosts:
    - CursoDebian
    - wst000f000

  tasks:
  
    - name: Ver los facts
      debug:
        var: ansible_facts
  
    - name: Install {{ servidor }}
      yum:
        name: "{{ servidor }}"
        state: latest

    - name: "{{ estado }} {{ servidor }}"
      service:
        name: "{{ servidor }}"
        enabled: true
        state: "{{ estado }}"
  
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest

    - name: Enable and start the firewall
      service:
        name: firewalld
        enabled: true
        state: started  
        
  handlers:
    - name: restart {{ servidor }}
      service:
        name: "{{ servidor }}"
        state: restarted

