---
# tasks file for myvhost
- name: Ensure apache 2 is installed
  yum:
    name: apache2
    state: latest

- name: Ensure apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: true

- name: vhost file is installed
  template: 
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache2

- name: Enable the new vhost
  command: a2ensite vhost.conf
  notify:
    - restart apache2

- name: Disable the default vhost
  command: a2dissite 000-default.conf
  notify:
    - restart apache2
